targets:
  $default:
    sources:
      - lib/**
      - openapi/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "openapi/"
          output_folder: "lib/generated/catalyst_gateway"
          separate_models: true