VERSION --try --global-cache 0.7

builder:
  FROM node:20-alpine
  WORKDIR /app
  COPY package.json package-lock.json .
  COPY index.html postcss.config.js tailwind.config.js tsconfig* vite.config.ts .eslintrc.yaml .prettierrc.yaml .
  COPY src ./src

  RUN npm i

check:
  FROM +builder

  RUN npm run check \
      && npm run lint

build:
  FROM +builder

  RUN npm run build

  SAVE ARTIFACT dist

local:
  FROM nginx:1.25-alpine

  COPY +build/dist /usr/share/nginx/html

  EXPOSE 80

  CMD ["nginx", "-g", "daemon off;"]

  SAVE IMAGE cat-wallet-connector:latest