chebotko_table: {
  shape: sql_table

  column_name_1: (CQL Type) {constraint: K}
  column_name_2: (CQL Type) {constraint: C↑}
  column_name_3: (CQL Type) {constraint: C↓}
  column_name_4: (CQL Type) {constraint: S}
  column_name_5: (CQL Type) {constraint: IDX}
  column_name_6: (CQL Type) {constraint: ++}
  "[column_name_7]": (CQL Type)
  "{column_name_8}": (CQL Type)
  "<column_name_9>": (CQL Type)
  "*column_name_10*": (UDT Name)
  "(column_name_11)": (CQL Type)
  column_name_12: (CQL Type)
}
