# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla
---
# Simple Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: scylladb
  namespace: scylla
spec:
  agentVersion: 3.2.8
  version: 5.4.3
  developerMode: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  #cpuset: true
  #network:
  #  hostNetworking: true
  datacenter:
    name: cluster
    racks:
      - name: test
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          capacity: 5Gi
          storageClassName: longhorn-strict-local

        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 4
            memory: 1Gi
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
  exposeOptions:
    nodeService:
      type: LoadBalancer
