[package]
name = "cat-data-service"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
event-db = { workspace = true }

clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "json", "time"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_with = { version = "3", features = ["macros"] }

tokio = { version = "1.8", features = ["rt", "macros", "rt-multi-thread"] }
thiserror = { version = "1.0" }
axum = { version = "0.6.9" }
metrics = { version = "0.21.1" }
metrics-exporter-prometheus = { version = "0.12.1" }

tower-http = { version = "0.4", features = ["cors"] }

rust_decimal = { workspace = true }

chrono = { workspace = true }

poem = { version = "1.3.58", features = ["embed", "prometheus", "compression", "test"] }
poem-openapi = { version = "3.0.4", features = [
    "openapi-explorer",
    "rapidoc",
    "redoc",
    "swagger-ui",
    "uuid",
    "url",
    "chrono",
] }
poem-extensions = { version = "0.7.2" }

# Metrics - Poem
opentelemetry-prometheus = { version = "0.13" }
opentelemetry = { workspace = true }
prometheus = { version = "0.13.0" }
cryptoxide = { workspace = true }
uuid = { workspace = true }
lazy_static = { workspace = true }
url = { workspace = true }
dotenvy = { workspace = true }
panic-message = "0.3"
regex = { workspace = true }
tower = { version = "0.4", features = ["util"] }
hyper = "0.14"
bytes = "1.4"
cpu-time = "1.0"
arc-swap = "1.6"
ulid = { version = "1.0.1", features = ["serde", "uuid"] }
rust-embed = "8"

[dev-dependencies]
quickcheck = { version = "0.9" }
quickcheck_macros = { version = "0.9" }
