name: example
version: 1.0.0
description: A project that showcases how to enable the recommended lints for Catalyst Flutter apps, packages, and plugins.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  catalyst_analysis:
    path: ../