VERSION 0.8

test:
    FROM earthly/dind:alpine-3.19-docker-25.0.5-r0
    COPY docker-compose.yml .
    COPY node1-scylla.yaml .
    COPY node2-scylla.yaml .
    COPY node3-scylla.yaml .
    COPY node4-scylla.yaml .
    ENV HOST_IP
    RUN export HOST_IP="$(ifconfig $(route -n | grep ^0.0.0.0 | awk '{print $NF}') | grep inet | grep -v inet6 | awk '{print $2}')"
    WITH DOCKER \
        --compose docker-compose.yml \
        --service scylla-node1 \
        --service scylla-node2 \
        --service scylla-node3 \
        --service scylla-node4 \
        --allow-privileged

       RUN echo 'lalala' && echo $HOST_IP

    END