name: catalyst_key_derivation
description: A Flutter plugin exposing CIP-1852 Cardano HD Key Derivation
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_key_derivation/catalyst_key_derivation
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

flutter:
  plugin:
    platforms:
      web:
        default_package: catalyst_key_derivation_web

dependencies:
  catalyst_key_derivation_platform_interface: ^0.1.0
  catalyst_key_derivation_web: ^0.3.0
  convert: ^3.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
