name: catalyst_key_derivation
description: "A flutter plugin that enables Cardano stye HD key derivation"
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_key_derivation
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
