VERSION 0.7

# cspell: words tqdm

load-mithril-snapshot:
    ARG network="preprod"

    FROM github.com/input-output-hk/catalyst-ci/earthly/python:v2.10.0+python-base
    
    RUN pip3 install requests
    RUN pip3 install tqdm

    COPY loader.py /scripts

    RUN /scripts/loader.py --network=$network --out="snapshot"
    SAVE ARTIFACT ./snapshot snapshot