VERSION --global-cache 0.7

builder:
    FROM github.com/input-output-hk/catalyst-ci/earthly/python:v2.7.0+python-base

    COPY --dir ./schema_mismatch README.md .
    DO github.com/input-output-hk/catalyst-ci/earthly/python:v2.7.0+BUILDER

build-tester:
    FROM +builder

    CMD poetry run pytest -vvvv --capture tee-sys --show-capture=stderr

gateway:
    FROM ../../+builder

    ENV CAT_ADDRESS=0.0.0.0:3030
    ENV DB_URL=postgres://catalyst-event-dev:CHANGE_ME@event-db/CatalystEventDev
    ENV LOG_LEVEL=debug

    COPY ../../+build/cat-gateway .
    CMD ./cat-gateway run \
        --address "$CAT_ADDRESS" \
        --database-url=$DB_URL \
        --log-level=$LOG_LEVEL

verify-schema-mismatch-behaviour:
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r4

    COPY ./docker-compose.yml .

    WITH DOCKER \
        --compose docker-compose.yml \
        --load event-db:latest=(../../event-db+build --with_historic_data=false) \
        --load cat-gateway:latest=(+gateway) \
        --load test=(+build-tester) \
        --service event-db \
        --service cat-gateway \
        --allow-privileged
        RUN docker run --network=default_default test
    END
