VERSION --global-cache 0.7

builder:
    FROM github.com/input-output-hk/catalyst-ci/earthly/python:v2.7.0+python-base

    COPY --dir ./schema_mismatch README.md .
    DO github.com/input-output-hk/catalyst-ci/earthly/python:v2.7.0+BUILDER

package-tester:
    FROM +builder

    CMD poetry run pytest
    # The following is useful for debugging the tests
    # CMD poetry run pytest -vvvv --capture tee-sys --show-capture=stderr

test:
    FROM earthly/dind:alpine

    WORKDIR /testing

    COPY ./docker-compose.yml .

    WITH DOCKER \
        --compose docker-compose.yml \
        --load event-db:latest=(../../event-db+build --with_historic_data=false) \
        --load cat-gateway:latest=(../+package-cat-gateway --address="127.0.0.1:3030" \
                                        --db_url="postgres://catalyst-event-dev:CHANGE_ME@localhost/CatalystEventDev") \
        --load test=(+package-tester) \
        --service event-db \
        --service cat-gateway \
        --allow-privileged
        RUN docker run --network=host test
    END
