name: catalyst_voices_dev
description: Shared test infrastructure for Catalyst Voices - fakes, mocks, and test utilities.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  catalyst_cardano: ^1.0.0
  catalyst_cardano_serialization: ^1.0.0
  catalyst_compression: ^1.0.0
  catalyst_key_derivation: ^1.0.0
  catalyst_voices_models:
    path: ../catalyst_voices_models
  catalyst_voices_repositories:
    path: ../catalyst_voices_repositories
  catalyst_voices_services:
    path: ../catalyst_voices_services
  catalyst_voices_shared:
    path: ../catalyst_voices_shared
  cbor: ^6.3.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.16.0
  mocktail: ^1.0.4
  test: ^1.25.15
  uuid_plus: ^0.1.0

dev_dependencies:
  catalyst_analysis: ^3.0.0
  
