VERSION 0.8
IMPORT github.com/input-output-hk/catalyst-ci/earthly/spectral:v3.2.21 AS spectral-ci

# cspell: words oapi
# test-lint-openapi - OpenAPI linting from an artifact
# testing whether the OpenAPI generated during build stage follows good practice.
test-lint-openapi:
    FROM spectral-ci+spectral-base
    # Copy the doc artifact.
    COPY --dir ../+build/doc .
    # Copy the spectral configuration file.
    COPY ./.oapi-v3.spectral.yml .spectral.yml
    # Scan the doc directory where type of file is JSON.
    DO spectral-ci+LINT --dir=./doc
