server {
    listen 80;


    location /api/gateway/ {
        rewrite ^/api/gateway/?(.*)$ /api/$1 break;
        proxy_pass http://cat-gateway:3030;
    }


    location / {
        proxy_pass http://cat-voices:8080;
    }
}