// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    documentsV2,
    documentAuthors,
    documentArtifacts,
    documentCollaborators,
    documentParameters,
    documentsLocalMetadata,
    localDocumentsDrafts,
    idxDocumentsV2TypeId,
    idxDocumentsV2TypeIdVer,
    idxDocumentsV2TypeRefId,
    idxDocumentsV2TypeRefIdVer,
    idxDocumentsV2RefIdVer,
    idxDocumentsV2TypeIdCreatedAt,
    idxDocumentsV2TypeRefIdRefVer,
    idxDocumentsV2TypeCreatedAt,
    idxDocumentsV2TypeTemplate,
    idxDocumentAuthorsComposite,
    idxDocumentAuthorsIdentity,
    idxDocumentAuthorsUsername,
    idxDocumentCollaboratorsComposite,
    idxDocumentCollaboratorsIdentity,
    idxDocumentCollaboratorsUsername,
    idxDocumentParametersComposite,
    idxLocalMetadataFavorite,
    idxLocalDraftsTypeAuthors,
    idxLocalDraftsTypeId,
    idxLocalDraftsCreatedAt,
  ];
  late final Shape0 documentsV2 = Shape0(
    source: i0.VersionedTable(
      entityName: 'documents_v2',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, ver)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 documentAuthors = Shape1(
    source: i0.VersionedTable(
      entityName: 'document_authors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(document_id, document_ver, account_id)',
        'FOREIGN KEY (document_id, document_ver) REFERENCES documents_v2(id, ver) ON DELETE CASCADE',
      ],
      columns: [_column_16, _column_17, _column_18, _column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 documentArtifacts = Shape2(
    source: i0.VersionedTable(
      entityName: 'document_artifacts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id, ver)',
        'FOREIGN KEY (id, ver) REFERENCES documents_v2(id, ver) ON DELETE CASCADE',
      ],
      columns: [_column_21, _column_4, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 documentCollaborators = Shape1(
    source: i0.VersionedTable(
      entityName: 'document_collaborators',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(document_id, document_ver, account_id)',
        'FOREIGN KEY (document_id, document_ver) REFERENCES documents_v2(id, ver) ON DELETE CASCADE',
      ],
      columns: [_column_16, _column_17, _column_18, _column_19, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 documentParameters = Shape3(
    source: i0.VersionedTable(
      entityName: 'document_parameters',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id, ver, document_id, document_ver)',
        'FOREIGN KEY (document_id, document_ver) REFERENCES documents_v2(id, ver) ON DELETE CASCADE',
      ],
      columns: [_column_19, _column_20, _column_4, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 documentsLocalMetadata = Shape4(
    source: i0.VersionedTable(
      entityName: 'documents_local_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 localDocumentsDrafts = Shape5(
    source: i0.VersionedTable(
      entityName: 'local_documents_drafts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, ver)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_23,
        _column_24,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxDocumentsV2TypeId = i1.Index(
    'idx_documents_v2_type_id',
    'CREATE INDEX idx_documents_v2_type_id ON documents_v2 (type, id)',
  );
  final i1.Index idxDocumentsV2TypeIdVer = i1.Index(
    'idx_documents_v2_type_id_ver',
    'CREATE INDEX idx_documents_v2_type_id_ver ON documents_v2 (type, id, ver)',
  );
  final i1.Index idxDocumentsV2TypeRefId = i1.Index(
    'idx_documents_v2_type_ref_id',
    'CREATE INDEX idx_documents_v2_type_ref_id ON documents_v2 (type, ref_id)',
  );
  final i1.Index idxDocumentsV2TypeRefIdVer = i1.Index(
    'idx_documents_v2_type_ref_id_ver',
    'CREATE INDEX idx_documents_v2_type_ref_id_ver ON documents_v2 (type, ref_id, ver)',
  );
  final i1.Index idxDocumentsV2RefIdVer = i1.Index(
    'idx_documents_v2_ref_id_ver',
    'CREATE INDEX idx_documents_v2_ref_id_ver ON documents_v2 (ref_id, ver)',
  );
  final i1.Index idxDocumentsV2TypeIdCreatedAt = i1.Index(
    'idx_documents_v2_type_id_created_at',
    'CREATE INDEX idx_documents_v2_type_id_created_at ON documents_v2 (type, id, created_at)',
  );
  final i1.Index idxDocumentsV2TypeRefIdRefVer = i1.Index(
    'idx_documents_v2_type_ref_id_ref_ver',
    'CREATE INDEX idx_documents_v2_type_ref_id_ref_ver ON documents_v2 (type, ref_id, ref_ver)',
  );
  final i1.Index idxDocumentsV2TypeCreatedAt = i1.Index(
    'idx_documents_v2_type_created_at',
    'CREATE INDEX idx_documents_v2_type_created_at ON documents_v2 (type, created_at)',
  );
  final i1.Index idxDocumentsV2TypeTemplate = i1.Index(
    'idx_documents_v2_type_template',
    'CREATE INDEX idx_documents_v2_type_template ON documents_v2 (type, template_id, template_ver)',
  );
  final i1.Index idxDocumentAuthorsComposite = i1.Index(
    'idx_document_authors_composite',
    'CREATE INDEX idx_document_authors_composite ON document_authors (document_id, document_ver, account_significant_id)',
  );
  final i1.Index idxDocumentAuthorsIdentity = i1.Index(
    'idx_document_authors_identity',
    'CREATE INDEX idx_document_authors_identity ON document_authors (account_significant_id)',
  );
  final i1.Index idxDocumentAuthorsUsername = i1.Index(
    'idx_document_authors_username',
    'CREATE INDEX idx_document_authors_username ON document_authors (username)',
  );
  final i1.Index idxDocumentCollaboratorsComposite = i1.Index(
    'idx_document_collaborators_composite',
    'CREATE INDEX idx_document_collaborators_composite ON document_collaborators (document_id, document_ver, account_significant_id)',
  );
  final i1.Index idxDocumentCollaboratorsIdentity = i1.Index(
    'idx_document_collaborators_identity',
    'CREATE INDEX idx_document_collaborators_identity ON document_collaborators (account_significant_id)',
  );
  final i1.Index idxDocumentCollaboratorsUsername = i1.Index(
    'idx_document_collaborators_username',
    'CREATE INDEX idx_document_collaborators_username ON document_collaborators (username)',
  );
  final i1.Index idxDocumentParametersComposite = i1.Index(
    'idx_document_parameters_composite',
    'CREATE INDEX idx_document_parameters_composite ON document_parameters (document_id, document_ver, id, ver)',
  );
  final i1.Index idxLocalMetadataFavorite = i1.Index(
    'idx_local_metadata_favorite',
    'CREATE INDEX idx_local_metadata_favorite ON documents_local_metadata (is_favorite)',
  );
  final i1.Index idxLocalDraftsTypeAuthors = i1.Index(
    'idx_local_drafts_type_authors',
    'CREATE INDEX idx_local_drafts_type_authors ON local_documents_drafts (type, authors_significant)',
  );
  final i1.Index idxLocalDraftsTypeId = i1.Index(
    'idx_local_drafts_type_id',
    'CREATE INDEX idx_local_drafts_type_id ON local_documents_drafts (type, id)',
  );
  final i1.Index idxLocalDraftsCreatedAt = i1.Index(
    'idx_local_drafts_created_at',
    'CREATE INDEX idx_local_drafts_created_at ON local_documents_drafts (created_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collaborators =>
      columnsByName['collaborators']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentType =>
      columnsByName['content_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parameters =>
      columnsByName['parameters']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get refId =>
      columnsByName['ref_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get refVer =>
      columnsByName['ref_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyId =>
      columnsByName['reply_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyVer =>
      columnsByName['reply_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get section =>
      columnsByName['section']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateId =>
      columnsByName['template_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateVer =>
      columnsByName['template_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ver =>
      columnsByName['ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<i2.Uint8List> _column_0(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authors',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'collaborators',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parameters',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ref_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ref_ver',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reply_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reply_ver',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'section',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'template_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'template_ver',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ver',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_15(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountSignificantId =>
      columnsByName['account_significant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get documentId =>
      columnsByName['document_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get documentVer =>
      columnsByName['document_ver']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_significant_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'username',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'document_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'document_ver',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<i2.Uint8List> get data =>
      columnsByName['data']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ver =>
      columnsByName['ver']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<i2.Uint8List> _column_21(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get documentId =>
      columnsByName['document_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get documentVer =>
      columnsByName['document_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ver =>
      columnsByName['ver']! as i1.GeneratedColumn<String>;
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isFavorite =>
      columnsByName['is_favorite']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<bool> _column_22(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_favorite',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_favorite" IN (0, 1))',
      ),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<i2.Uint8List> get content =>
      columnsByName['content']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get authors =>
      columnsByName['authors']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collaborators =>
      columnsByName['collaborators']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentType =>
      columnsByName['content_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parameters =>
      columnsByName['parameters']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get refId =>
      columnsByName['ref_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get refVer =>
      columnsByName['ref_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyId =>
      columnsByName['reply_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get replyVer =>
      columnsByName['reply_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get section =>
      columnsByName['section']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateId =>
      columnsByName['template_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get templateVer =>
      columnsByName['template_ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ver =>
      columnsByName['ver']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorsNames =>
      columnsByName['authors_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get authorsSignificant =>
      columnsByName['authors_significant']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authors_names',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'authors_significant',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from3To4: from3To4),
);
