VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.1.21 AS rust-ci

# builder : Set up our target toolchains, and copy our files.
builder:
    DO rust-ci+SETUP

    COPY --dir .cargo .config Cargo.* clippy.toml deny.toml rustfmt.toml src examples .

# check : Run basic check.
check:
    FROM +builder

    DO rust-ci+EXECUTE --cmd="/scripts/std_checks.py"

# build : Build the C509 library
build:
    FROM +builder

    DO rust-ci+EXECUTE \
        --cmd="/scripts/std_build.py" \
        --args1="--libs=c509-certificate"

    RUN cargo install wasm-pack --version=0.12.1 --locked

# js-wasm-package-locally : Generate the wasm package and save it locally
js-wasm-package-locally:
    FROM +build
    RUN wasm-pack build --target web
    SAVE ARTIFACT ./pkg AS LOCAL ./pkg
