name: Bug Report
description: File a bug report
title: "[Bug]: "
type: "bug"
labels: ["in triage"]
projects: ["input-output-hk/102"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Specify the project that has been impacted by the bug.
      options:
        - Athena
        - Frontend
        - Backend
        - Flutter/Dart packages
        - Rust crates
        - Documentation
        - Other (specify in Anything else section)
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **If you selected Frontend as Project please include the relevant component in the issue title:**

              [account.registration] [proposal.builder] [proposal.view]
              [workspace] [proposals] [discovery]

        👉 **Example:** `[Bug][discovery] Crash on login`

  - type: textarea
    attributes:
      label: Version
      description: Specify the version/release/commit that has been impacted by the bug
    validations:
      required: true

  - type: dropdown
    id: OS
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - macOS
        - Linux
        - iOS
        - Android
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Arc
        - Other (specify in Anything else section)
        - Not Applicable
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Catalyst App/Browser/OS version? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/input-output-hk/catalyst-voices/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
