blank_issues_enabled: true
contact_links:
  - name: Catalyst Voices Discussions
    url: https://github.com/input-output-hk/catalyst-voices/discussions
    about: Please ask and answer questions here.
