name: "🏛️ Epic"
description: Create a new Epic.
title: "🏛️ [EPIC] : <title>"
labels: ["epic"]
projects: ["/input-output-hk/102"]
body:
  - type: markdown
    attributes:
      value: "⚠️ **Epics are only to be created by the Project Managers!** ⚠️"
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "Short Summary of the Epic"
      placeholder: "Short Summary"
    validations:
      required: true
  - type: input
    id: jira-epic
    attributes:
      label: "JIRA Epic"
      description: All Epics must have a linked Jira [EPIC](https://input-output.atlassian.net/jira/software/c/projects/NPG/issues)
      placeholder: ex. https://input-output.atlassian.net/browse/NPG-8294
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Extended Description of the Epic"
      placeholder: "Explicit extended description of the epic..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## TODO Lists

  - type: textarea
    id: todo
    attributes:
      label: "Todo"
      description: "Grouped Todo lists. Each links to its issue, when created."
      placeholder: |
        ### <list 1 name>

        - [ ] #1 
        - [ ] #2
        - [ ] issue description when not yet created.

        ### <list 2 name>

        - [ ] #3
        - [ ] #4
        - [ ] issue description when not yet created.

      value: |
        ### <list 1 name>

        - [ ] #1 
        - [ ] #2
        - [ ] issue description when not yet created.

        ### <list 2 name>

        - [ ] <issue>
        - [ ] <issue>
        - [ ] <issue>

    validations:
      required: true
