name: Test Case
description: Create a test case
title: "[Test Case]: <title>"
labels: ["testcase"]
projects: ["/input-output-hk/102"]
body:
  - type: textarea
    attributes:
      label: Objective
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: References
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Preconditions
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Instructions
      description: A concise description of what you expected to happen.
      placeholder: |
        ### <list 1 name>

        - [ ] #1
        - [ ] #2
        - [ ] issue description when not yet created.

        ### <list 2 name>

        - [ ] #3
        - [ ] #4
        - [ ] issue description when not yet created.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Notes
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
