global_options:
  catalyst_voices_repositories|openapi_pre_process_builder:
    runs_before:
      - swagger_dart_code_generator:swagger_dart_code_generator
      - chopper_generator:chopper_generator

targets:
  $default:
    sources:
      - lib/**
      - openapi/**
      - $package$
      - pubspec.*
    builders:
      catalyst_voices_repositories|openapi_pre_process_builder:
        options:
          sourcepath: "openapi/source"
      swagger_dart_code_generator:
        options:
          input_folder: "openapi/processed"
          output_folder: "lib/generated/api"
          separate_models: true
          include_if_null: false
          exclude_paths:
            - /api/draft/*
            - /api/v1/health/*
          # turn it off when we can get rid of vit. atm its generating classes incorrectly with it.
          use_path_for_request_names: true
          overriden_models:
            - file_name: "vit"
              import_url: "../../src/api/models/overridden_models.dart"
              overriden_models:
                - SimpleProposal$ProposalCategory
                - SimpleProposal$Proposer
                - CommunityChoiceProposal$ProposalCategory
                - CommunityChoiceProposal$Proposer
      json_serializable:
        options:
          explicit_to_json: true
      chopper_generator:
        options:
          header: "// Generated code"

      drift_dev:
        # disable drift's default builder, we're using the modular setup instead.
        enabled: false
      drift_dev:analyzer:
        enabled: true
        # Drift build options, as per https://drift.simonbinder.eu/docs/advanced-features/builder_options/
        options: &options # Use ISO 8601 string instead of a unix timestamp
          store_date_time_values_as_text: true
          # Potentially turn this on if gradual updates will be needed.
          data_class_to_companions: false
          # Can not turn this on because of cat-gateway endpoints generation
          fatal_warnings: false
          # We're not using it right now
          generate_manager: false
          sql:
            dialect: sqlite
            options:
              # Note that these options are used for static analysis only and don't have an
              # impact on the actual sqlite version at runtime.
              # https://drift.simonbinder.eu/generation_options/?h=dialect#assumed-sql-environment
              version: "3.45"
              # See modules here https://drift.simonbinder.eu/generation_options/?h=dialect#multi-dialect-code-generation
              modules:
                - json1

          # To use the make-migrations command
          databases:
            catalyst_database: lib/src/database/catalyst_database.dart

          # The directory where the test files are stored:
          test_dir: test/src/database/migration/
          # The directory where the schema files are stored:
          schema_dir: drift_schemas/
      drift_dev:modular:
        enabled: true
        # We use yaml anchors to give the two builders the same options
        options: *options

builders:
  openapi_pre_process_builder:
    import: "package:catalyst_voices_repositories/builders/builders.dart"
    builder_factories: [ "openApiPreProcessBuilder" ]
    build_extensions: { ".json": [ ".processed.json" ] }
    auto_apply: root_package
    build_to: source
    applies_builders: [ "swagger_dart_code_generator" ]
    defaults:
      options:
        sourcepath: "openapi/source"
