VERSION 0.8

# start-cluster : starts the local development cluster
# Needs both Vagrant and Virtualbox installed on the local machine.
start-cluster:
    LOCALLY
    # Check if the necessary tools are present locally
    RUN kubectl version --client=true
    RUN helm version --short
    # Check if the necessary local DNS entries exist
    RUN python scripts/check-cluster-dns.py ./shared/extra.hosts
    # Everything checks out so far, try and start the cluster.
    RUN vagrant up
    # Add default services
    # Add grafana/loki

# stop-cluster : stops the locally running cluster
stop-cluster:
    LOCALLY
    RUN vagrant destroy -f

# test-cluster : Checks if the cluster is running on the local machine.
test-cluster:
    LOCALLY
    RUN kubectl --kubeconfig shared/k3s.yaml -o wide get nodes

# kubernetes-base : base container with tooling set up for local access
kubernetes-base:
    FROM alpine:3.19
    
    # Install kubectl
    RUN apk update && \
        apk upgrade && \
        apk add kubectl \
                helm

    COPY shared/k3s.yaml $HOME/.kube/config

    COPY --dir manifests manifests

# test targets to deploy the local documentation
deploy-docs:
    FROM +kubernetes-base

    RUN kubectl apply -f manifests/docs.yml

# test target to stop the local documentation
stop-docs:
    FROM +kubernetes-base

    RUN kubectl delete deployment cat-gateway-docs
    RUN kubectl delete service cat-gateway-docs

# show-info : list important info about the running cluster
show-info:
    FROM +kubernetes-base
    
    # RUN kubectl --kubeconfig shared/k3s.yaml -o wide get nodes
    RUN --no-cache kubectl -n kube-system get all
    RUN --no-cache kubectl -o wide get nodes
    RUN --no-cache kubectl -o wide get pods
    RUN --no-cache kubectl -o wide get service
