name: catalyst_key_derivation_web
description: Web platform implementation of catalyst_key_derivation. Exposes a CIP-1852 Cardano HD Key Derivation.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_key_derivation/catalyst_key_derivation_web
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.1"

flutter:
  plugin:
    implements: catalyst_key_derivation
    platforms:
      web:
        pluginClass: CatalystKeyDerivationWeb
        fileName: catalyst_key_derivation_web.dart

  assets:
    - assets/js/

dependencies:
  catalyst_key_derivation_platform_interface: ^0.1.0
  convert: ^3.1.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  catalyst_analysis: ^2.0.0
  flutter_test:
    sdk: flutter
