name: cardano_multiplatform_lib_web
description: Web platform implementation of cardano_multiplatform_lib
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/utilities/cardano_multiplatform_lib/cardano_multiplatform_lib_web
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [blockchain, cardano, cryptocurrency, wallet]
version: 1.0.0

environment:
  sdk: ^3.3.0
  flutter: 3.19.5

flutter:
  plugin:
    implements: cardano_multiplatform_lib
    platforms:
      web:
        pluginClass: CardanoMultiplatformLibPlugin
        fileName: cardano_multiplatform_lib_web.dart

dependencies:
  cardano_multiplatform_lib_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.0

dev_dependencies:
  catalyst_analysis:
    path: ../../catalyst_analysis
  flutter_test:
    sdk: flutter
