block = [
    block_header,
    block_data,
    validator_signature,
]

block_header = [
    tree_id: #6.32780(bytes), ; ULID type
    chain_id: #6.32780(bytes), ; ULID type
    ?type: block_type, ;
    timestamp: ~#6.1(uint .ge 1722470400), ; Epoch-based date/time
    validator,
    ?metadata,
    prev_block_id: hash_bytes, ; Hash of the previous block
]

validator = (kid / [2* kid])
validator_signature = (bytes / [2* bytes])

block_data = ~#6.24(bytes) ; Encoded CBOR data item
metadata = ~#6.24(bytes) ; Encoded CBOR data item

kid = bytes .size 16 ; 128 bites hash of the x509/c509 certificate

block_type = &("Genesis": 0, "Final": 1)

hash_bytes = (
  #6.18556([2525, bytes]) \ ; Blake3 hash
  #6.18556([2526, bytes]) \ ; Blake2b hash
  #6.18556([2527, bytes]) ; Blake2s hash
)
