VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.6.10 AS python-ci

package:
    FROM python-ci+python-base

    WORKDIR /app

    ARG tag='latest'

    COPY pyproject.toml .
    COPY uv.lock .
    COPY set_config.py .

    COPY --dir dev .
    COPY --dir preprod .
    COPY --dir prod .

    COPY entrypoint.sh .
    RUN chmod +x entrypoint.sh

    ENTRYPOINT ["/app/entrypoint.sh"]

    SAVE IMAGE voices-frontend-config:${tag}

docker:
    FROM +package

    ARG container="voices-frontend-config"
    ARG tag="latest"

    SAVE IMAGE ${container}:${tag}