name: poc_local_storage
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  file_picker: ^8.0.7
  flutter_secure_storage: ^9.2.2
  pointycastle: ^3.9.1
  crypto: ^3.0.5
  asn1lib: ^1.5.3

dev_dependencies:
  catalyst_analysis: ^1.2.0

dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1

flutter:
  uses-material-design: true
