VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.6.14 AS python-ci
IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.6.14 AS rust-ci

builder:
    DO rust-ci+SETUP
    DO python-ci+INSTALL

    WORKDIR /app

    ARG tag='latest'

    COPY pyproject.toml .
    COPY uv.lock .
    COPY setup_fund.py .

    COPY --dir dev .
    
    COPY entrypoint.sh .
    RUN chmod +x entrypoint.sh
    RUN uv sync

    ENTRYPOINT ["/app/entrypoint.sh"]

    SAVE IMAGE setup-fund-documents:${tag}

docker:
    FROM +builder

    ARG container="setup-fund-documents"
    ARG tag="latest"

    SAVE IMAGE ${container}:${tag}