VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:v3\.2\.28 AS docs-ci


# update-docs-dev-script: get the latest docs dev script from CI.
update-docs-dev-script:
    DO docs-ci+SYNC_LOCAL_DOCS