VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:chore/upgrade-flutter-3-29-0 AS docs-ci


# update-docs-dev-script: get the latest docs dev script from CI.
update-docs-dev-script:
    DO docs-ci+SYNC_LOCAL_DOCS