# References to the rules 
# OpenAPI: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#openapi-rules
# OWASP Top 10: https://github.com/stoplightio/spectral-owasp-ruleset/blob/v1.4.3/src/ruleset.ts
# Documentations: https://github.com/stoplightio/spectral-documentation/blob/v1.3.1/src/ruleset.ts

# cspell: words OWASP owasp

# Use CDN hosted version for spectral-documentation and spectral-owasp
extends:
- 'spectral:oas'
- 'https://unpkg.com/@stoplight/spectral-documentation@1.3.1/dist/ruleset.mjs'
- 'https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.4.3/dist/ruleset.mjs'

aliases:
  PathItem:
  - $.paths[*]
  OperationObject:
  - $.paths[*][get,put,post,delete,options,head,patch,trace]
  DescribableObjects:
  - $.info
  - $.tags[*]
  - '#OperationObject'
  - '#OperationObject.responses[*]'
  - '#PathItem.parameters[?(@ && @.in)]'
  - '#OperationObject.parameters[?(@ && @.in)]'

overrides:
- files: ['*']
  rules:
    # Override document description rule
    # - No limitations on the characters that can start or end a sentence.
    # - Length should be >= 20 characters
    docs-description:
      given: '#DescribableObjects'
      then:
      - field: 'description'
        function: 'truthy'
      - field: 'description'
        function: 'length'
        functionOptions:
          min: 20

    # Severity
    # warn: Should be implemented, but is blocked by a technical issue.
    # info: Good to be implemented.

    # Rate limit
    owasp:api4:2019-rate-limit: warn
    owasp:api4:2019-rate-limit-responses-429: warn
    # Public API
    owasp:api2:2019-protection-global-safe: info
    owasp:api2:2019-protection-global-unsafe: info
    owasp:api2:2019-protection-global-unsafe-strict: info
    owasp:api3:2019-define-error-responses-401: warn

- files:
  - '**#/paths/~1api~1health~1live/get/responses'
  - '**#/paths/~1api~1health~1started/get/responses'
  - '**#/paths/~1api~1health~1ready/get/responses'
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/post/responses'
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/get/responses'
  # Recheck this, already apply validator but does not work "FragmentId"
  - '**#/paths/~1api~1v1~1fragments~1statuses/get/parameters/0/schema'
  # Recheck this, already apply validator but does not work "AccountId"
  - '**#/paths/~1api~1v1~1votes~1plan~1account-votes~1%7Baccount_id%7D/get/parameters/0/schema'
  rules:
    owasp:api4:2019-string-restricted: off

- files:
  - '**#/paths/~1api~1health~1live/get/responses'
  - '**#/paths/~1api~1health~1started/get/responses'
  - '**#/paths/~1api~1health~1ready/get/responses'
  - '**#/paths/~1api~1v0~1message/post/requestBody/content'
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/post/responses'
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/get/responses'
  - '**#/components/schemas/ServerErrorPayload/properties/id'
  - '**#/components/schemas/VoterRegistration/properties/as_at'
  - '**#/components/schemas/VoterRegistration/properties/last_updated'
  # Recheck this, already apply validator but does not work "FragmentId"
  - '**#/paths/~1api~1v1~1fragments~1statuses/get/parameters/0/schema'
  # Recheck this, already apply validator but does not work "AccountId"
  - '**#/paths/~1api~1v1~1votes~1plan~1account-votes~1%7Baccount_id%7D/get/parameters/0/schema'
  rules:
    owasp:api4:2019-string-limit: off

- files:
  - '**#/paths/~1api~1v0~1vote~1active~1plans/get/responses'
  - '**#/paths/~1api~1v1~1votes~1plan~1account-votes~1%7Baccount_id%7D/get/responses'
  rules:
    owasp:api4:2019-array-limit: off

- files:
  - '**#/components/schemas/FragmentStatus'
  rules:
    owasp:api6:2019-no-additionalProperties: off

- files:
  - '**#/paths/~1api~1v1~1fragments~1statuses/get/responses'
  rules:
    owasp:api6:2019-constrained-additionalProperties: off

- files:
  # Ignore event_id
  - '**#/paths/~1api~1registration~1voter~1%7Bvoting_key%7D/get/parameters/1/schema'
  # Ignore the test id
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/post/parameters/0/schema'
  - '**#/paths/~1api~1test~1test~1%7Bid%7D~1test~1%7Baction%7D/get/parameters/0/schema'
  rules:
    owasp:api1:2019-no-numeric-ids: off

