# References to the rules 
# OpenAPI: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#openapi-rules
# OWASP Top 10: https://github.com/stoplightio/spectral-owasp-ruleset/blob/v1.4.3/src/ruleset.ts
# Documentations: https://github.com/stoplightio/spectral-documentation/blob/v1.3.1/src/ruleset.ts

# cspell: words OWASP owasp

# Use CDN hosted version for spectral-documentation and spectral-owasp
extends:
- 'spectral:oas'
- 'https://unpkg.com/@stoplight/spectral-documentation@1.3.1/dist/ruleset.mjs'
- 'https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.4.3/dist/ruleset.mjs'

aliases:
  PathItem:
  - $.paths[*]
  OperationObject:
  - $.paths[*][get,put,post,delete,options,head,patch,trace]
  DescribableObjects:
  - $.info
  - $.tags[*]
  - '#OperationObject'
  - '#OperationObject.responses[*]'
  - '#PathItem.parameters[?(@ && @.in)]'
  - '#OperationObject.parameters[?(@ && @.in)]'

overrides:
- files: ['*']
  rules:
    # Override document description rule
    # - No limitations on the characters that can start or end a sentence.
    # - Length should be >= 20 characters
    docs-description:
      given: '#DescribableObjects'
      then:
      - field: 'description'
        function: 'truthy'
      - field: 'description'
        function: 'length'
        functionOptions:
          min: 20

    # Severity
    # warn: Should be implemented, but is blocked by a technical issue.
    # info: Good to be implemented.

    # Rate limit
    owasp:api4:2019-rate-limit: warn
    owasp:api4:2019-rate-limit-responses-429: warn
    # Public API
    owasp:api2:2019-protection-global-unsafe: info
    owasp:api2:2019-protection-global-unsafe-strict: info
    owasp:api3:2019-define-error-responses-401: off
