VERSION --try --global-cache 0.7

#cspell: words rustfmt toolsets USERARCH

# Set up our target toolchains, and copy our files.
builder:
    DO github.com/input-output-hk/catalyst-ci/earthly/rust:v2.7.0+SETUP

    COPY --dir .cargo .config Cargo.* clippy.toml deny.toml rustfmt.toml bin crates tests .

## -----------------------------------------------------------------------------
##
## Standard CI targets.
##
## These targets are discovered and executed automatically by CI.

# Run check using the most efficient host tooling
# CI Automated Entry point.
check:
    FROM +builder

    RUN /scripts/std_checks.py

# Test which runs check with all supported host tooling.  Needs qemu or rosetta to run.
# Only used to validate tooling is working across host toolsets.
all-hosts-check:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +check

build:
    # Build the service
    FROM +builder

    TRY
        RUN /scripts/std_build.py   --cov_report="coverage-report.info" \
                                    --bins="cat-gateway/cat-gateway"
    FINALLY
        SAVE ARTIFACT target/nextest/ci/junit.xml AS LOCAL cat-gateway.junit-report.xml
        SAVE ARTIFACT coverage-report.info AS LOCAL cat-gateway.coverage-report.info
    END
    RUN ./target/$TARGETARCH/release/cat-gateway docs ./target/$TARGETARCH/doc/cat-gateway-api.json
    SAVE ARTIFACT target/$TARGETARCH/doc doc
    SAVE ARTIFACT target/$TARGETARCH/release/cat-gateway cat-gateway

# Test which runs check with all supported host tooling.  Needs qemu or rosetta to run.
# Only used to validate tooling is working across host toolsets.
all-hosts-build:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build

package-cat-gateway:
    FROM alpine:3.19
    ARG tag="latest"
    ARG address
    ARG db_url
    ARG log_level="error"
    RUN apk upgrade --no-cache && apk add --no-cache gcc
    COPY +build/cat-gateway .
    ENTRYPOINT ./cat-gateway run --address $address --database-url $db_url --log-level $log_level
    SAVE IMAGE cat-gateway:$tag
    
# Publish packages if all integration tests have passed. (Failure to pass tests will prevent packages being published.)
# publish:
#    FROM scratch

## -----------------------------------------------------------------------------

# This step simulates the full CI run for local purposes only.
local-ci-run:
    BUILD +check
    BUILD +build
    # BUILD +package
    # BUILD +publish
