VERSION 0.8

IMPORT ../../.. AS catalyst-voices

integration-test-web:
    FROM catalyst-voices+code-generator
    ARG TARGETARCH
    ARG browser
    LET driver_port = 4444

    IF [ $browser = "chrome" ]
        LET driver = "chromedriver"
    END

    IF [ $browser = "firefox" ]
        LET driver = "geckodriver"
    END
    # Commenting out Edge tests as they are failing due to:
    # https://github.com/flutter/flutter/issues/76213
    # https://github.com/flutter/flutter/issues/142021
    # IF [ $browser = "edge" && $TARGETARCH = "amd64" ]]
    #    LET driver = "msedgedriver"
    # END

    WORKDIR /frontend/apps/voices

    RUN ($driver --port=$driver_port > $driver.log &) && \
        sleep 5 && \
        flutter drive --driver=test_driver/integration_tests.dart \
            --target=integration_test/all_test.dart \
            -d web-server --browser-name=$browser --driver-port=$driver_port \
            # https://github.com/flutter/flutter/issues/154727
            --web-browser-flag=--disable-web-security \
            --web-browser-flag=--disable-gpu \
            --web-browser-flag=--headless \
            --web-browser-flag=--disable-search-engine-choice-screen \
            --profile
# TODO(oldgreg): make tests run without failing workflow until issue #2407 is released
#           --profile || echo fail > fail
    WAIT
        SAVE ARTIFACT $driver.log AS LOCAL $driver.log
    END

#    IF [ -f fail ]
        RUN --no-cache echo ""$browser" integration test failed" && \
            echo "Printing "$driver" logs..." && \
            cat $driver.log && \
#            exit 1
    END

# TODO(dtscalac): disabled integration tests due to them being flaky,
# reenable when enable-threads.js workaround is removed
# and https://github.com/fzyzcjy/flutter_rust_bridge/issues/2407 closed
test-web-all:
    BUILD +integration-test-web \
            --browser=chrome
