VERSION 0.8

IMPORT ../../.. AS catalyst-voices

integration-test-web:
    FROM catalyst-voices+builder
    ARG TARGETARCH
    ARG browser
    LET driver_port = 4444

    IF [ $browser = "chrome" ]
        LET driver = "chromedriver"
    END

    IF [ $browser = "firefox" ]
        LET driver = "geckodriver"
    END
    # Commenting out Edge tests as they are failing due to:
    # https://github.com/flutter/flutter/issues/76213
    # https://github.com/flutter/flutter/issues/142021
    # IF [ $browser = "edge" && $TARGETARCH = "amd64" ]]
    #    LET driver = "msedgedriver"
    # END
    
    WORKDIR /frontend/apps/voices

    RUN ($driver --port=$driver_port > $driver.log &) && \
        sleep 5 && \
        flutter drive --driver=test_driver/integration_tests.dart \
            --target=integration_test/app_test.dart \
            -d web-server --browser-name=$browser --driver-port=$driver_port \
            # https://github.com/flutter/flutter/issues/154727
            --web-browser-flag=--disable-web-security \
            --web-browser-flag=--disable-gpu \
            --web-browser-flag=--headless=old \
            --web-browser-flag=--disable-search-engine-choice-screen \
            --profile || echo fail > fail
    WAIT
        SAVE ARTIFACT $driver.log AS LOCAL $driver.log
    END
    
    IF [ -f fail ]
        RUN --no-cache echo ""$browser" integration test failed" && \
            echo "Printing "$driver" logs..." && \
            cat $driver.log && \
            exit 1
    END

test-web-all:
    BUILD +integration-test-web \
            --browser=chrome \
            --browser=firefox
