VERSION 0.8

IMPORT ../../.. AS catalyst-voices

integration-test-web:
    FROM catalyst-voices+code-generator
    ARG TARGETARCH
    ARG browser
    LET driver_port = 4444

    IF [ $browser = "chrome" ]
        LET driver = "chromedriver"
    END

    IF [ $browser = "firefox" ]
        LET driver = "geckodriver"
    END
    # Commenting out Edge tests as they are failing due to:
    # https://github.com/flutter/flutter/issues/76213
    # https://github.com/flutter/flutter/issues/142021
    # IF [ $browser = "edge" && $TARGETARCH = "amd64" ]]
    #    LET driver = "msedgedriver"
    # END

    WORKDIR /frontend/apps/voices

    RUN ($driver --port=$driver_port > $driver.log &) && \
        flutter doctor -v && \
        cat /usr/local/bin/chrome-patch.sh && \
        sleep 5 && \
        flutter drive --driver=test_driver/integration_tests.dart \
            --target=integration_test/all_test.dart \
            -d $browser --driver-port=$driver_port
            --web-header Cross-Origin-Opener-Policy=same-origin \
            --web-header Cross-Origin-Embedder-Policy=require-corp \
            --profile || echo fail > fail
    WAIT
        SAVE ARTIFACT $driver.log AS LOCAL $driver.log
    END

    IF [ -f fail ]
        RUN --no-cache echo ""$browser" integration test failed" && \
            echo "Printing "$driver" logs..." && \
            cat $driver.log && \
            exit 1
    END

# TODO(oldgreg): investigate failures in ci
disable-nightly-test-web-all:
    BUILD +integration-test-web \
            --browser=chrome
