kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-best-effort-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
