VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.4.7 AS python-ci
IMPORT github.com/input-output-hk/catalyst-libs/rust:catalyst-types-v0.0.5 AS cat-libs-rust
IMPORT github.com/input-output-hk/catalyst-libs/rust:r20250724-01 AS dep-cat-libs-rust
IMPORT github.com/input-output-hk/catalyst-storage AS cat-storage

builder:
    FROM python-ci+python-base

    # prepare tests
    COPY --dir ./api .
    COPY --dir ./integration .
    COPY --dir ./scripts .
    COPY --dir ./test_data .
    COPY --dir ./utils .
    COPY --dir ./wrappers .
    COPY cat-libs-rust+build/mk_signed_doc .
    # mk_signed_doc cli tool for building deprecated version of documents 
    COPY dep-cat-libs-rust+build/mk_signed_doc ./dep_mk_signed_doc
    COPY cat-storage+cardano-asset-preprod/cardano-asset-preprod.json .
    DO python-ci+BUILDER

# Creates a package of the python integration test runner
package:
    FROM +builder

    ENV ASSETS_DATA_PATH="./cardano-asset-preprod.json"
    ENV MK_SIGNED_DOC_PATH="./mk_signed_doc"
    ENV DEP_MK_SIGNED_DOC_PATH="./dep_mk_signed_doc"

    ENTRYPOINT ["poetry", "run", "pytest", "-m", "preprod_indexing or unmarked", "-s", "--junitxml", "junit-report.xml", "--cov", "integration", "--cov-report", "lcov" ]
    SAVE IMAGE api-tests-runner:latest
