name: catalyst_cose_platform_interface
description: A common platform interface for the catalyst_cose plugin.
repository: https://github.com/input-output-hk/catalyst-voices/tree/main/catalyst_voices_packages/catalyst_cose/catalyst_cose_platform_interface
issue_tracker: https://github.com/input-output-hk/catalyst-voices/issues
topics: [cryptography, encryption, codec]
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  cbor: ^6.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  catalyst_analysis:
    path: ../../catalyst_analysis
  flutter_test:
    sdk: flutter
