; Permissionless Authorization using RBAC Certificates for Catalyst.
;
; Token Data Definition

auth-token-v1 = bytes .cborseq auth-token-v1-fields

; Note: This is NOT an array it is a set of fields in a cbor sequence.
auth-token-v1-fields = [ kid, ulid, signature ]

; Key ID - Blake2b-128 hash of the Role 0 Certificate defining the Session public key.
; This Certificate defines the cryptography used to sign the token.
; Current, ONLY ed25519 is supported, but other signature cryptography may be allowed in future.
kid = (bstr .size 16)

; ULID - Identifier for this token, encodes both the time the token was issued and a random nonce.
ulid = (bstr .size 16)

; Signature - ED25519 Signature over the preceding two fields.
; Must be signed using the Private Key of the Role 0 Certificate identified by the Kid field.
signature = (bstr .size 64)

; Example Signed Token
; # CBOR sequence with 3 elements
; 50                                  # bytes(16)
;    00112233445566778899AABBCCDDEEFF 
; 50                                  # bytes(16)
;    01912CEC71CF2C4C14A55D5585D94D7B 
; 58 40                               # bytes(64)
;    00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
;
; Where:
;   kid       = 0x00112233445566778899aabbccddeeff
;   ulid      = 0x01912cec71cf2c4c14a55d5585d94d7b
;   signature = 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 
