VERSION 0.8

IMPORT ../catalyst-gateway AS catalyst-gateway
IMPORT github.com/input-output-hk/catalyst-ci/earthly/flutter:fix/flutter-builder-ci AS flutter-ci

# If running this target with a local ssh agent active, set the environment
# variable EARTHLY_SSH_AUTH_SOCK='' to make the `+deps` target work. Earthly
# defaults to ssh authentication when it founds an ssh agent active but the
# flutter repo needs to be cloned via https to properly use the `channel`
# subcommand.
deps:
    FROM debian:bookworm-slim
    ARG TARGETARCH
    ARG FLUTTER_VERSION=3.22.1
    RUN apt-get update
    RUN apt-get install -y git curl unzip bzip2 bash jq gpg lcov
    COPY --dir test_driver/scripts .
    RUN chmod +x scripts/install-chrome-linux64.sh && ./scripts/install-chrome-linux64.sh
    RUN chmod +x scripts/install-edge-linux64.sh && ./scripts/install-edge-linux64.sh
    RUN chmod +x scripts/install-firefox-linux64.sh && ./scripts/install-firefox-linux64.sh

    WORKDIR /frontend

    RUN git clone --depth 1 --branch $FLUTTER_VERSION https://github.com/flutter/flutter.git /usr/local/flutter
    ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:$HOME/.pub-cache/bin:${PATH}"
    RUN flutter --version
    RUN flutter doctor -v
    RUN flutter config --enable-web
    RUN dart pub global activate melos
    RUN dart pub global activate junitreport
    RUN dart pub global activate coverage

src:
    FROM +deps
    COPY ../+repo-catalyst-voices-all/repo .
    RUN melos bootstrap

# code-generator - Generates flutter code.
# Based on Catalyst Gateway OpenAPI specifications generates models, clients
# and serialization logic.
# It accepts [save_locally] ARG that when true place the artifacts in the
# proper folder of `catalyst_voices_services` local code.
code-generator:
    ARG save_locally=false

    FROM +src
    WORKDIR /frontend/catalyst_voices/packages/catalyst_voices_services
    COPY catalyst-gateway+build/doc/cat-gateway-api.json openapi/cat-gateway-api.json
    RUN flutter pub get
    RUN dart run build_runner build --delete-conflicting-outputs

    IF [ $save_locally = true ]
        SAVE ARTIFACT lib/generated/catalyst_gateway/* AS LOCAL ./packages/catalyst_voices_services/lib/generated/catalyst_gateway/
    ELSE
        SAVE ARTIFACT lib/generated/catalyst_gateway
    END

# check-flutter-code-generator - Checks that the code generation is consistent
# with the generated code currently in the repo.
# TODO: enable it
flutter-code-generator:
    FROM +code-generator
    # Copy generated files in the local file tree to a temporary folder
    COPY packages/catalyst_voices_services/lib/generated/catalyst_gateway /tmp/repo_generated
    # Check diff between local code and earthly artifacts
    RUN diff /tmp/repo_generated lib/generated/catalyst_gateway

check-static-analysis:
    FROM +src
    RUN melos analyze --fatal-infos --fatal-warnings

check-code-formatting:
    FROM +src
    RUN melos run format-check

# Build web version of Catalyst Voices
build:
    FROM +src

    WORKDIR /frontend/catalyst_voices
    RUN flutter clean
    RUN flutter pub get
    RUN flutter build web --web-renderer canvaskit --release --target lib/configs/main_web.dart

    WORKDIR /frontend/catalyst_voices/build
    SAVE ARTIFACT web /web AS LOCAL web

test-unit:
    FROM +src
    RUN melos run test-report
    WAIT
        SAVE ARTIFACT test_reports AS LOCAL test_reports
    END

package:
    FROM nginx:alpine3.18
    ARG tag='latest'
    COPY +build/web /app
    COPY ./nginx.conf /etc/nginx/nginx.conf
    EXPOSE 80

    SAVE IMAGE voices-frontend:$tag

publish:
    FROM +package
    ARG tag='latest'

    SAVE IMAGE voices-frontend:$tag

# check-cat-voices-license - Check the license of catalyst_voices.
check-cat-voices-license:
    FROM flutter-ci+license-checker-base
    # catalyst_voices depends on catalyst_voices_packages
    COPY ../+repo-catalyst-voices-all/repo .
    RUN mv base catalyst_voices/base
    WORKDIR /frontend/catalyst_voices
    DO flutter-ci+LICENSE_CHECK
