name: catalyst_voices
repository: https://github.com/minikin/didactic-parakeet/

packages:
  - lib/**
  - packages/**
  - 'tests/*'

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    # branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  lint:
    run: melos run analyze
    description: Run all static analysis checks.

  format:
      run: melos exec dart format . --fix
      description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  metrics:
    run: |
      melos exec -c 1 --ignore="*example*" -- \
        flutter pub run dart_code_metrics:metrics analyze
    description: |
      Run `dart_code_metrics` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  test:select:
    run: melos exec -- flutter test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- flutter test --coverage &&
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/
    description: Generate coverage for the selected package.

  build:pub_get:all:
    run: flutter pub get
    exec:
      concurrency: 6
    description: Install all dependencies