name: catalyst_voices
repository: https://github.com/input-output-hk/catalyst-voices

packages:
  - apps/**
  - packages/internal/**
  - packages/libs/**
  - utilities/**

ignore:
  # ignore flutter_rust_bridge packages that are non-conformant with melos
  - packages/libs/catalyst_key_derivation/example/**
  # ignore temporary packages that are non-conformant with melos
  - apps/voices/build/**

permittedLicenses:
  - MIT
  - Apache-2.0
  - Unicode-DFS-2016
  - BSD-3-Clause
  - BSD-2-Clause
  - BlueOak-1.0.0
  - Apache-2.0 WITH LLVM-exception
  - CC0-1.0

packageLicenseOverride:
  fuchsia_remote_debug_protocol: BSD-3-Clause
  flutter_driver: BSD-3-Clause
  flutter_localizations: BSD-3-Clause
  flutter_test: BSD-3-Clause
  flutter_web_plugins: BSD-3-Clause
  integration_test: BSD-3-Clause
  rxdart: Apache-2.0
  vector_math: Apache-2.0
  sky_engine: Apache-2.0
  flutter_gen: MIT
  # catalyst packages
  catalyst_analysis: Apache-2.0
  catalyst_cose: Apache-2.0
  catalyst_cardano_serialization: Apache-2.0
  catalyst_cardano_platform_interface: Apache-2.0
  catalyst_compression: Apache-2.0
  catalyst_compression_web: Apache-2.0
  catalyst_cardano_web: Apache-2.0
  catalyst_compression_platform_interface: Apache-2.0
  catalyst_key_derivation: Apache-2.0
  catalyst_key_derivation_web: Apache-2.0
  catalyst_key_derivation_platform_interface: Apache-2.0
  catalyst_voices_assets: Apache-2.0
  catalyst_voices_assets_example: Apache-2.0
  catalyst_cardano: Apache-2.0
  catalyst_cardano_example: Apache-2.0
  catalyst_voices_localization: Apache-2.0
  catalyst_voices_models: Apache-2.0
  example: Apache-2.0
  remote_widgets: Apache-2.0
  remote_widgets_example: Apache-2.0
  catalyst_voices_view_models: Apache-2.0
  catalyst_voices_blocs: Apache-2.0
  catalyst_voices_driver: Apache-2.0
  catalyst_voices_shared: Apache-2.0
  catalyst_voices_brands: Apache-2.0
  catalyst_voices_services: Apache-2.0
  poc_local_storage: Apache-2.0
  catalyst_voices_repositories: Apache-2.0
  catalyst_voices: Apache-2.0
  uikit_example: Apache-2.0

packageSourceOverride:
  fuchsia_remote_debug_protocol: https://github.com/flutter/flutter/blob/main/LICENSE
  flutter_driver: https://github.com/flutter/flutter/blob/main/LICENSE
  flutter_localizations: https://github.com/flutter/flutter/blob/main/LICENSE
  flutter_test: https://github.com/flutter/flutter/blob/main/LICENSE
  flutter_web_plugins: https://github.com/flutter/flutter/blob/main/LICENSE
  integration_test: https://github.com/flutter/flutter/blob/main/LICENSE
  rxdart: https://github.com/ReactiveX/rxdart/blob/master/LICENSE
  vector_math: https://github.com/google/vector_math.dart/blob/master/LICENSE
  sky_engine: https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/LICENSE
  flutter_gen: https://github.com/FlutterGen/flutter_gen/blob/main/LICENSE

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
  bootstrap:
    runPubGetInParallel: true
    environment:
      sdk: ">=3.8.0 <4.0.0"
      flutter: ">=3.32.8"
    dependencies:
      auto_size_text: ^3.0.0
      async: ^2.13.0
      asn1lib: ^1.6.5
      bip39: ^1.0.6
      bloc_concurrency: ^0.3.0
      bloc_test: ^10.0.0
      chopper: ^8.3.0
      collection: ^1.19.1
      cryptography: ^2.7.0
      cupertino_icons: ^1.0.8
      dotted_border: ^3.1.0
      ed25519_hd_key: ^2.3.0
      email_validator: ^3.0.0
      equatable: ^2.0.7
      fake_async: ^1.3.3
      ffi: ^2.1.4
      ffigen: ^19.1.0
      file_picker: ^10.2.1
      flutter_bloc: ^9.1.1
      flutter_dropzone: ^4.2.1
      flutter_inappwebview: ^6.1.5
      flutter_localized_locales: ^2.0.5
      flutter_markdown: ^0.7.7+1
      flutter_native_splash: ^2.4.6
      # TODO(minikin): We use our forks as a temporary workaround for F14.
      flutter_quill:
        git:
          url: https://github.com/input-output-hk/flutter-quill
          ref: 532172254c3cee957bbdbb08be922f2c870b7fff
      flutter_quill_extensions:
        git:
          url: https://github.com/input-output-hk/flutter-quill
          path: flutter_quill_extensions
          ref: 532172254c3cee957bbdbb08be922f2c870b7fff
      flutter_rust_bridge: 2.11.1
      flutter_secure_storage: ^9.2.4
      formz: ^0.8.0
      go_router: ^15.1.3
      intl: ^0.20.2
      logging: ^1.3.0
      lottie: ^3.3.1
      markdown: ^7.3.0
      # TODO(minikin): We use our forks as a temporary workaround for F14.
      markdown_quill:
        git:
          url: https://github.com/input-output-hk/markdown_quill
          ref: a523a6128e6b2677739ac5d68d1d9c65a2af8b98
      meta: ^1.16.0
      result_type: ^1.0.0
      rxdart: ^0.28.0
      password_strength: ^0.2.0
      plugin_platform_interface: ^2.1.8
      bech32: ^0.2.2
      bip32_ed25519: ^0.6.2
      # TODO(damian): un-pin version when cbor will expose EncodeSink, .encode, Arg.
      # RawTransaction requires those internal classes.
      cbor: 6.3.7
      convert: ^3.1.2
      path: ^1.9.1
      package_info_plus: ^8.3.0
      pinenacl: ^0.6.0
      pool: ^1.5.1
      uuid_plus: ^0.1.0
      sentry_flutter: ^9.6.0
      scrollable_positioned_list: ^0.3.8
      shared_preferences: ^2.5.3
      shared_preferences_platform_interface: ^2.4.1
      skeletonizer: ^2.1.0+1
      synchronized: ^3.4.0
      typed_data: ^1.4.0
      web: ^1.1.1
      webdriver: ^3.1.0
    dev_dependencies:
      test: ^1.25.15
      build_runner: ^2.5.4
      chopper_generator: ^8.2.0
      flutter_gen_runner: ^5.11.0
      go_router_builder: ^2.9.0
      mocktail: ^1.0.4
      sentry_dart_plugin: ^3.1.1

scripts:
  l10n:
    run: |
      melos exec -c 1 --scope="catalyst_voices_localization" -- flutter gen-l10n
    description: |
      Run `flutter gen-l10n` in catalyst_voices_localization package to generate l10n bindings.

  build_runner:
    run: |
      melos exec -c 1 \
      --depends-on="build_runner" \
      --ignore="catalyst_voices_repositories" -- \
          dart run build_runner build --delete-conflicting-outputs
    description: |
      Run `build_runner` in every package which contains the build_runner dependency.
      The catalyst_voices_repositories is skipped because to run a build_runner there you
      must generate first swagger docs (see related Earthfile).

  build_runner_repository:
    run: |
      melos exec -c 1 --depends-on="build_runner" --scope="catalyst_voices_repositories" -- dart run build_runner clean && \
      melos exec -c 1 --scope="catalyst_voices_repositories" -- dart run process_openapi.dart && \
      melos exec -c 1 \
      --depends-on="build_runner" \
      --scope="catalyst_voices_repositories" -- dart run build_runner build --delete-conflicting-outputs
    description: |
      Run `build_runner` in catalyst_voices_repositories package

  db-make-migration:
    run: |
      melos exec -c 1 \
      --depends-on="build_runner" \
      --scope="catalyst_voices_repositories" -- \
          dart run drift_dev make-migrations
    description: |
      Run `make-migrations` in catalyst_voices_repositories package and generates schema migration
      classes

  metrics:
    run: |
      melos exec -c 1 -- \
        flutter pub run dart_code_metrics:metrics analyze
    description: |
      Run `dart_code_metrics` in all packages.
      - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format-apply:
    run: |
      melos exec -c 1 --dir-exists="lib" -- "find lib -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format {} +" &&
      melos exec -c 1 --dir-exists="test" -- "find test -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format {} +" &&
      melos exec -c 1 --dir-exists="integration_test" -- "find integration_test -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format {} +"
    description: Run `dart format` for all packages.

  format-check:
    run: |
      melos exec -c 1 --dir-exists="lib" -- "find lib -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format --output none --set-exit-if-changed {} +" &&
      melos exec -c 1 --dir-exists="test" -- "find test -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format --output none --set-exit-if-changed {} +" &&
      melos exec -c 1 --dir-exists="integration_test" -- "find integration_test -name '*.dart' ! -name '*.g.dart' ! -path '*/generated/*' ! -path '*/.dart_tool/*' -exec dart format --output none --set-exit-if-changed {} +"
    description: Run `dart format` checks for all packages.

  license-check:
    run: |
      melos exec -- lic_ck check-licenses -c $MELOS_ROOT_PATH/melos.yaml -i
    description: Run `lic_ck` checks for all packages.

  license-list:
    run: |
      melos exec --ignore="catalyst_analysis" --ignore="example" -- \
        'dart run $MELOS_ROOT_PATH/scripts/generate_licenses.dart $MELOS_PACKAGE_PATH $MELOS_ROOT_PATH/docs/licenses/$MELOS_PACKAGE_NAME.csv'
      dart run $MELOS_ROOT_PATH/scripts/merge_csv_files.dart $MELOS_ROOT_PATH/docs/licenses/ $MELOS_ROOT_PATH/docs/licenses/licenses.csv
      echo "✅ Output file: $MELOS_ROOT_PATH/docs/licenses/licenses.csv"
    description: Generate license list for all packages in docs/licenses/licenses.csv file.

  dependency-graph:
    run: |
      dart pub global activate pubviz
      melos exec --scope "catalyst_voices" -- \
        'pubviz print --direct-dependencies --production-dependencies --format dot > $MELOS_ROOT_PATH/docs/dependency_graph.dot'
      echo "✅ Output file: $MELOS_ROOT_PATH/docs/dependency_graph.dot"
    description: |
      Generate license list for all packages in docs/dependency_graph.dot file.
      The .dot file can be viewed using software available online such as graphviz.

  test:select:
    run: |
      melos exec -c 1 --dir-exists="test" -- flutter test
    description: Run `flutter test` for selected packages.

  test-native:
    run: |
      melos run test:select --no-select
    description: Run `flutter test` for all packages.

  # catalyst_voices: this package should contain only widget tests
  test-web:
    run: |
      melos exec -c 1 --dir-exists="test" --ignore="catalyst_voices" -- flutter test --platform chrome
    description: Run `flutter test --platform chrome` for all packages.

  test-report-web:
    run: |
      # cleanup from previous build and create empty folder where test reports will be stored
      rm -fR $MELOS_ROOT_PATH/test_reports
      mkdir $MELOS_ROOT_PATH/test_reports

      # cleanup old coverage files and create empty folder where coverage files will be stored
      find . -type d -name coverage -prune -exec rm -rf {} \;
      mkdir $MELOS_ROOT_PATH/coverage
      # run tests, generate junit reports in /test_reports/ & code coverage report
      melos exec -c 1 --dir-exists="test" --ignore="catalyst_voices" -- \
      ' TESTS_OUTPUT_FILE="$MELOS_ROOT_PATH/test_reports/$MELOS_PACKAGE_NAME.tests-output.json"
        JUNIT_REPORT_FILE="$MELOS_ROOT_PATH/test_reports/$MELOS_PACKAGE_NAME.junit-report.xml"
        flutter test --platform chrome --reporter github --file-reporter=json:$TESTS_OUTPUT_FILE --coverage ; \
        EXIT_CODE=$? ; \
        cat $TESTS_OUTPUT_FILE | tojunit --output $JUNIT_REPORT_FILE ; \
        exit $EXIT_CODE'

      # store the exit code after running the tests,
      # this is the exit code for the whole script
      EXIT_CODE=$?

      # removes code coverage for generated code
      find . -name "*.lcov.info" -exec \
        lcov --remove {} -o {} --ignore-errors unused,unused \
        '*.g.dart' \
        '*.freezed.dart' \
        '*.chopper.dart' \
        '*.swagger.dart' \
        '*.openapi.dart' \
        '*.gen.dart' \
        '*.swagger.*.dart' \
        '*.drift.dart' \
        'lib/generated/**' \;

      # merges all coverage reports into a single one and puts it in /coverage/lcov.info
      dart pub global run combine_coverage --repo-path=.
      mv ./coverage/lcov.info ./coverage/lcov.coverage.info

      exit $EXIT_CODE

    description: |
      Run `flutter test --platform chrome` for all packages and generate junit and coverage reports.
      The test reports are saved in /test_reports folder.
      The coverages are saved in coverage/lcov.info file for each tested package.
      The combined coverage is saved in the /coverage/lcov.coverage.info file.

  test-report-native:
    run: |
      # cleanup from previous build and create empty folder where test reports will be stored
      rm -fR $MELOS_ROOT_PATH/test_reports
      mkdir $MELOS_ROOT_PATH/test_reports

      # cleanup old coverage files and create empty folder where coverage files will be stored
      find . -type d -name coverage -prune -exec rm -rf {} \;
      mkdir $MELOS_ROOT_PATH/coverage
      # run tests, generate junit reports in /test_reports/ & code coverage report
      melos exec -c 1 --dir-exists="test" -- \
      ' TESTS_OUTPUT_FILE="$MELOS_ROOT_PATH/test_reports/$MELOS_PACKAGE_NAME.tests-output.json"
        JUNIT_REPORT_FILE="$MELOS_ROOT_PATH/test_reports/$MELOS_PACKAGE_NAME.junit-report.xml"
        flutter test --reporter github --file-reporter=json:$TESTS_OUTPUT_FILE --coverage ; \
        EXIT_CODE=$? ; \
        cat $TESTS_OUTPUT_FILE | tojunit --output $JUNIT_REPORT_FILE ; \
        exit $EXIT_CODE'

      # store the exit code after running the tests,
      # this is the exit code for the whole script
      EXIT_CODE=$?

      # removes code coverage for generated code
      find . -name "*.lcov.info" -exec \
        lcov --remove {} -o {} --ignore-errors unused,unused \
        '*.g.dart' \
        '*.freezed.dart' \
        '*.chopper.dart' \
        '*.swagger.dart' \
        '*.openapi.dart' \
        '*.gen.dart' \
        '*.swagger.*.dart' \
        '*.drift.dart' \
        'lib/generated/**' \;

      # merges all coverage reports into a single one and puts it in /coverage/lcov.info
      dart pub global run combine_coverage --repo-path=.
      mv ./coverage/lcov.info ./coverage/lcov.coverage.info

      exit $EXIT_CODE

    description: |
      Run `flutter test` for all packages and generate junit and coverage reports.
      The test reports are saved in /test_reports folder.
      The coverages are saved in coverage/lcov.info file for each tested package.
      The combined coverage is saved in the /coverage/lcov.coverage.info file.

  l10n-check:
    run: |
      cd packages/internal/catalyst_voices_localization && dart lib/src/manage_l10n.dart --check
    description: |
      Check for unused translation keys in .arb files without modifying them, and check if translation keys are sorted.

  l10n-clean:
    run: |
      cd packages/internal/catalyst_voices_localization && dart lib/src/manage_l10n.dart --clean --sort
    description: |
      Clean up unused translation keys and sort them alphabetically in .arb files.

  docs-generate:
    run: |
      dart pub global activate dartdoc 8.0.5
      melos exec -c 1 --scope="*catalyst_voices*" --ignore="*example*" -- flutter analyze && 
      melos exec -c 1 --scope="*catalyst_voices*" --ignore="*example*" -- dart doc --output=MELOS_ROOT_PATH/docs/dartdoc/MELOS_PACKAGE_NAME .

    description: |
      Generate internal documentation and saves it to docs/dartdoc directory

  docs-view:
    steps:
      - dart pub global activate dhttpd
      - dart pub global run dhttpd --path docs/dartdoc/

    description: |
      Documentation will be served at localhost:8080/<packageName>
      For example catalyst_voices_repository is served at localhost:8080/catalyst_voices_repository
