# Set the Earthly version to 0.7
VERSION 0.7

# cspell: words mkdocs runable

# Copy all the source we need to build the docs
src:
    FROM github.com/input-output-hk/catalyst-ci/earthly/docs:feat/docs3+mkdocs-material

    # Just copy the actual doc src here.
    COPY --dir src includes macros overrides mkdocs.yml /docs

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir ../+repo-docs/repo /docs/includes

# Build the docs here.
docs:
    FROM +src

    DO github.com/input-output-hk/catalyst-ci/earthly/docs:feat/docs3+BUILD

# Make a locally runable container that can serve the docs.
local:
    # Build a self contained service to show built docs locally.
    DO github.com/input-output-hk/catalyst-ci/earthly/docs:feat/docs3+PACKAGE

    # Copy the static pages into the container
    COPY +docs/ /usr/share/nginx/html

    # This is a local only image, we do not publish it.
    SAVE IMAGE cat-voices-docs:latest