VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:v3.2.21 AS docs-ci

IMPORT .. AS repo
IMPORT ../catalyst-gateway AS catalyst-gateway
IMPORT ../catalyst-gateway/event-db AS event-db

# cspell: words mkdocs runable

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO docs-ci+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir repo+repo-docs/repo /docs/includes
    # copy Rust docs
    COPY catalyst-gateway+build/doc /docs/src/api/cat-gateway/rust-docs

    # Copy docs we build in the postgres example.
    COPY --dir event-db+build/docs src/architecture/08_concepts/event_db


# Build the docs here.
docs:
    FROM +src

    DO docs-ci+BUILD

# local : Make a locally runable container that can serve the docs.
#   --push will cause this image to be pushed to the local development cluster
#   --local_registry : Set this to the hostname of your local registry or "" to inhibit.
local:
    # Change this to point to another local registry, OR set to "" to disable
    # pushing to a local registry even if `--push` is passed.
    # this should be "registry.cluster.test:5000" but Earthly can not reliably locate it in a hosts file.
    ARG local_registry="192.168.58.10:5000"
    # ARG local_registry="registry.cluster.test"
    # Build a self contained service to show built docs locally.
    DO docs-ci+PACKAGE

    # Copy the static pages into the container
    COPY +docs/ /usr/share/nginx/html

    # This is a local only image, we do not publish it.
    SAVE IMAGE cat-voices-docs:latest

    # Publish to the local development cluster
    IF [ "$local_registry" != "" ]
        SAVE IMAGE --push --insecure $local_registry/cat-voices-docs:latest
    END
