INHERIT: std-theme.yml

# cspell: words cips

# Project Information
site_name: Project Catalyst - Catalyst Voices
site_url: https://input-output-hk.github.io/catalyst-docs

# Repository
repo_name: input-output-hk/catalyst-voices
repo_url: https://github.com/input-output-hk/catalyst-voices

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Getting Started: getting-started/index.md
      - Quick Start: getting-started/quick-start.md
      - Advanced: getting-started/advanced.md
      - Development: getting-started/development.md
  - Monorepo Architecture:
      - Monorepo Architecture: monorepo-architecture/index.md
  - Catalyst Standards:
      - Catalyst Standards: catalyst-standards/index.md
      - Draft CIPs:
          - Draft CIPs: catalyst-standards/draft-cips/index.md
          - Role Registration: catalyst-standards/draft-cips/role-registration/cip-xxxx.md
          - RBAC CIP30 Extension: catalyst-standards/draft-cips/rbac-cip30-extension/cip-xxxx.md
          - Catalyst Voting CIP30 Extension: catalyst-standards/draft-cips/catalyst-vote-signing-cip30-extension/cip-xxxx.md
      - Catalyst Ballot Formats:
          - Catalyst Ballot Formats: catalyst-standards/ballot/index.md
          - Catalyst V1 Ballot: catalyst-standards/ballot/catalyst-v1.md
          - Catalyst V2 Ballot: catalyst-standards/ballot/catalyst-v2.md
  - Appendix:
      - Appendix: appendix/index.md
      - Important Information:
          - Important Information: appendix/important/index.md
          - Contributing: appendix/important/contributing.md
          - Code of Conduct: appendix/important/coc.md
          - Security: appendix/important/security.md
          - License: appendix/important/license.md
