name: catalyst_voices_assets_example
description: A Catalyst Voices Assets Example.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: 3.19.1

dependencies:
  catalyst_voices_assets:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true