name: catalyst_voices_view_models
description: Catalyst Voices ViewModels.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: 3.19.1

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  formz: ^0.7.0

dev_dependencies:
   catalyst_analysis:
    path: ../../../catalyst_voices_packages/catalyst_analysis
   test: ^1.24.9