// Mocks generated by Mockito 5.4.4 from annotations
// in catalyst_voices_repositories/test/src/catalyst_data_gateway_repository/catalyst_data_gateway_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:catalyst_voices_services/generated/catalyst_gateway/cat_gateway_api.enums.swagger.dart'
    as _i6;
import 'package:catalyst_voices_services/generated/catalyst_gateway/cat_gateway_api.models.swagger.dart'
    as _i7;
import 'package:catalyst_voices_services/generated/catalyst_gateway/cat_gateway_api.swagger.dart'
    as _i2;
import 'package:chopper/chopper.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeType_0 extends _i1.SmartFake implements Type {
  _FakeType_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CatGatewayApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatGatewayApi extends _i1.Mock implements _i2.CatGatewayApi {
  @override
  _i3.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _i4.dummyValue<_i3.ChopperClient>(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.ChopperClient);

  @override
  set client(_i3.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
        returnValueForMissingStub: _FakeType_0(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);

  @override
  _i5.Future<_i3.Response<dynamic>> apiTestTestIdTestActionGet({
    required int? id,
    required String? action,
    List<_i6.Animals>? pet,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiTestTestIdTestActionGet,
          [],
          {
            #id: id,
            #action: action,
            #pet: pet,
          },
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiTestTestIdTestActionGet,
            [],
            {
              #id: id,
              #action: action,
              #pet: pet,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiTestTestIdTestActionGet,
            [],
            {
              #id: id,
              #action: action,
              #pet: pet,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> apiTestTestIdTestActionPost({
    required int? id,
    required String? action,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiTestTestIdTestActionPost,
          [],
          {
            #id: id,
            #action: action,
          },
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiTestTestIdTestActionPost,
            [],
            {
              #id: id,
              #action: action,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiTestTestIdTestActionPost,
            [],
            {
              #id: id,
              #action: action,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> apiHealthStartedGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiHealthStartedGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthStartedGet,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthStartedGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> apiHealthReadyGet() => (super.noSuchMethod(
        Invocation.method(
          #apiHealthReadyGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthReadyGet,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthReadyGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> apiHealthLiveGet() => (super.noSuchMethod(
        Invocation.method(
          #apiHealthLiveGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthLiveGet,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<dynamic>>.value(
            _i4.dummyValue<_i3.Response<dynamic>>(
          this,
          Invocation.method(
            #apiHealthLiveGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<_i7.StakeInfo>> apiCardanoStakedAdaStakeAddressGet({
    required String? stakeAddress,
    _i6.Network? network,
    int? slotNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiCardanoStakedAdaStakeAddressGet,
          [],
          {
            #stakeAddress: stakeAddress,
            #network: network,
            #slotNumber: slotNumber,
          },
        ),
        returnValue: _i5.Future<_i3.Response<_i7.StakeInfo>>.value(
            _i4.dummyValue<_i3.Response<_i7.StakeInfo>>(
          this,
          Invocation.method(
            #apiCardanoStakedAdaStakeAddressGet,
            [],
            {
              #stakeAddress: stakeAddress,
              #network: network,
              #slotNumber: slotNumber,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<_i7.StakeInfo>>.value(
                _i4.dummyValue<_i3.Response<_i7.StakeInfo>>(
          this,
          Invocation.method(
            #apiCardanoStakedAdaStakeAddressGet,
            [],
            {
              #stakeAddress: stakeAddress,
              #network: network,
              #slotNumber: slotNumber,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<_i7.StakeInfo>>);

  @override
  _i5.Future<_i3.Response<_i7.SyncState>> apiCardanoSyncStateGet(
          {_i6.Network? network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiCardanoSyncStateGet,
          [],
          {#network: network},
        ),
        returnValue: _i5.Future<_i3.Response<_i7.SyncState>>.value(
            _i4.dummyValue<_i3.Response<_i7.SyncState>>(
          this,
          Invocation.method(
            #apiCardanoSyncStateGet,
            [],
            {#network: network},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<_i7.SyncState>>.value(
                _i4.dummyValue<_i3.Response<_i7.SyncState>>(
          this,
          Invocation.method(
            #apiCardanoSyncStateGet,
            [],
            {#network: network},
          ),
        )),
      ) as _i5.Future<_i3.Response<_i7.SyncState>>);

  @override
  _i5.Future<_i3.Response<_i7.VoterRegistration>>
      apiRegistrationVoterVotingKeyGet({
    required String? votingKey,
    int? eventId,
    bool? withDelegators,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiRegistrationVoterVotingKeyGet,
              [],
              {
                #votingKey: votingKey,
                #eventId: eventId,
                #withDelegators: withDelegators,
              },
            ),
            returnValue: _i5.Future<_i3.Response<_i7.VoterRegistration>>.value(
                _i4.dummyValue<_i3.Response<_i7.VoterRegistration>>(
              this,
              Invocation.method(
                #apiRegistrationVoterVotingKeyGet,
                [],
                {
                  #votingKey: votingKey,
                  #eventId: eventId,
                  #withDelegators: withDelegators,
                },
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i3.Response<_i7.VoterRegistration>>.value(
                    _i4.dummyValue<_i3.Response<_i7.VoterRegistration>>(
              this,
              Invocation.method(
                #apiRegistrationVoterVotingKeyGet,
                [],
                {
                  #votingKey: votingKey,
                  #eventId: eventId,
                  #withDelegators: withDelegators,
                },
              ),
            )),
          ) as _i5.Future<_i3.Response<_i7.VoterRegistration>>);

  @override
  _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>> apiV0MessagePost(
          {required Object? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV0MessagePost,
          [],
          {#body: body},
        ),
        returnValue:
            _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>.value(
                _i4.dummyValue<_i3.Response<_i7.FragmentsProcessingSummary>>(
          this,
          Invocation.method(
            #apiV0MessagePost,
            [],
            {#body: body},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>.value(
                _i4.dummyValue<_i3.Response<_i7.FragmentsProcessingSummary>>(
          this,
          Invocation.method(
            #apiV0MessagePost,
            [],
            {#body: body},
          ),
        )),
      ) as _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>);

  @override
  _i5.Future<_i3.Response<List<_i7.VotePlan>>> apiV0VoteActivePlansGet() =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV0VoteActivePlansGet,
          [],
        ),
        returnValue: _i5.Future<_i3.Response<List<_i7.VotePlan>>>.value(
            _i4.dummyValue<_i3.Response<List<_i7.VotePlan>>>(
          this,
          Invocation.method(
            #apiV0VoteActivePlansGet,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<List<_i7.VotePlan>>>.value(
                _i4.dummyValue<_i3.Response<List<_i7.VotePlan>>>(
          this,
          Invocation.method(
            #apiV0VoteActivePlansGet,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Response<List<_i7.VotePlan>>>);

  @override
  _i5.Future<_i3.Response<List<_i7.AccountVote>>>
      apiV1VotesPlanAccountVotesAccountIdGet({required String? accountId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #apiV1VotesPlanAccountVotesAccountIdGet,
              [],
              {#accountId: accountId},
            ),
            returnValue: _i5.Future<_i3.Response<List<_i7.AccountVote>>>.value(
                _i4.dummyValue<_i3.Response<List<_i7.AccountVote>>>(
              this,
              Invocation.method(
                #apiV1VotesPlanAccountVotesAccountIdGet,
                [],
                {#accountId: accountId},
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i3.Response<List<_i7.AccountVote>>>.value(
                    _i4.dummyValue<_i3.Response<List<_i7.AccountVote>>>(
              this,
              Invocation.method(
                #apiV1VotesPlanAccountVotesAccountIdGet,
                [],
                {#accountId: accountId},
              ),
            )),
          ) as _i5.Future<_i3.Response<List<_i7.AccountVote>>>);

  @override
  _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>> apiV1FragmentsPost(
          {required _i7.FragmentsBatch? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1FragmentsPost,
          [],
          {#body: body},
        ),
        returnValue:
            _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>.value(
                _i4.dummyValue<_i3.Response<_i7.FragmentsProcessingSummary>>(
          this,
          Invocation.method(
            #apiV1FragmentsPost,
            [],
            {#body: body},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>.value(
                _i4.dummyValue<_i3.Response<_i7.FragmentsProcessingSummary>>(
          this,
          Invocation.method(
            #apiV1FragmentsPost,
            [],
            {#body: body},
          ),
        )),
      ) as _i5.Future<_i3.Response<_i7.FragmentsProcessingSummary>>);

  @override
  _i5.Future<_i3.Response<Object>> apiV1FragmentsStatusesGet(
          {required List<String>? fragmentIds}) =>
      (super.noSuchMethod(
        Invocation.method(
          #apiV1FragmentsStatusesGet,
          [],
          {#fragmentIds: fragmentIds},
        ),
        returnValue: _i5.Future<_i3.Response<Object>>.value(
            _i4.dummyValue<_i3.Response<Object>>(
          this,
          Invocation.method(
            #apiV1FragmentsStatusesGet,
            [],
            {#fragmentIds: fragmentIds},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.Response<Object>>.value(
            _i4.dummyValue<_i3.Response<Object>>(
          this,
          Invocation.method(
            #apiV1FragmentsStatusesGet,
            [],
            {#fragmentIds: fragmentIds},
          ),
        )),
      ) as _i5.Future<_i3.Response<Object>>);
}
