# TODO(minikin): Temporary disabled until we have useful integration tests.

# IMPORT ../ AS catalyst-voices

# integration-test-web:
#     FROM catalyst-voices+build-web
#     ARG TARGETARCH
#     ARG browser
#     LET driver_port = 4444

#     IF [ $browser = "chrome" ]
#         LET driver = "chromedriver"
#     END

#     IF [ $browser = "firefox" ]
#         LET driver = "geckodriver"
#     END
#     # Commenting out Edge tests as they are failing due to:
#     # https://github.com/flutter/flutter/issues/76213
#     # https://github.com/flutter/flutter/issues/142021
#     #IF [ $browser = "edge" && $TARGETARCH = "amd64" ]]
#     #    LET driver = "msedgedriver"
#     #END
#     RUN ($driver --port=$driver_port > $driver.log &) && \
#             flutter drive --driver=test_driver/integration_tests.dart \
#                 --target=integration_test/main.dart \
#                     --flavor development -d web-server --profile \
#                         --browser-name=$browser --driver-port=$driver_port || echo fail > fail
#     # Using WAIT instead of TRY because TRY/CATCH/FINALLY does not (currently) support expanding args for SAVE ARTIFACT paths
#     WAIT
#         SAVE ARTIFACT $driver.log AS LOCAL $driver.log
#     END
#     IF [ -f fail ]
#         RUN echo ""$browser" integration test failed" && \
#             echo "Printing "$driver" logs..." && \
#             cat $driver.log && \
#             exit 1
#     END

# test-web-all:
#     BUILD +integration-test-web \
#             --browser=chrome \
#             --browser=firefox
