name: Allure Report Generation

on:
  push:

permissions:
    contents: write


concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  generate-allure:
    name: Generate allure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages # branch name
          path: gh-pages-dir # checkout path

      - name: Allure Report Action
        uses: mgrybyk/allure-report-branch-action@v1
        if: always()
        continue-on-error: true
        id: allure # used in comment to PR
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages-dir'
          report_dir: './allure-results'

      - name: Git Commit and Push Action
        uses: mgrybyk/git-commit-pull-push-action@v1
        if: always()
        with:
          repository: gh-pages-dir
          branch: gh-pages
          pull_args: --rebase -X ours