name: Spell Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    name: Check spelling across all files
    uses: input-output-hk/catalyst-ci/.github/workflows/spell-check.yml@v2.0.6
