VERSION 0.8

IMPORT ../../ AS cat-voice-ci

# check-license - Check the license of catalyst_cardano_serialization.
check-license:
    DO cat-voice-ci+LICENSE_CHECK --path=catalyst_voices_packages/catalyst_cardano_serialization